### PR TITLE
Adds a functional dropdown to EventList

### PR DESCRIPTION
**Pull request by llincker**
Improves the dropdown and adds functionalities!
(using the code in [this tutorial](http://fareez.info/blog/create-your-own-autocomplete-using-vuejs/) as a basis).
Here's the result:
productsdropdown
When the user clicks on the input field, it shows all products that he can select, and if he types some letters, it only shows the products containing the letters (search functionality).
The user can navigate through all products with the up and down keys, and he can select the product he wants by clicking on it or pressing the enter key.
When the user first clicks on the input, it clears the field and shows all products, he doesn't have to erase all the letters of the previous product.
He can add products by clicking on the +, and remove them by clicking on the x.

### CODE REVIEW

**Review by tiberiusferreira — CHANGES_REQUESTED** [review]
Cool! Love when sites propose the search functionality!
Just one thing: I think your indentation is a not the same as the one already used in the project.
So it looks like you are modifying the whole file when you are not. It also makes it harder to review. 
Do you mind changing it so it matches the one already in use?

**Comment by llincker** [comment]
Of course, I'm sorry I haven't realized it sooner!

**Comment by llincker** [comment]
Done! It took 3 commits, because I had to do it by hand, my autoindent tool doesn't work the same as yours I think, it wants to remove indents where it shouldn't!

**Review by LoicBer — APPROVED** [review]
It's ok for me :+1:

**Review by tiberiusferreira — APPROVED** [review]

**Pull request merged**
